### ISSUE TITLE
Add copy button

### ISSUE THREAD

**Issue by strarsis** [aucor/polylang-copy-content#3]
It would be nice if the whole post could be copied over an existing translation (post) 
by using a button in Polylang metabox, this is handy sometimes.

**Comment by TeemuSuoranta** [comment]
Do you have some example use cases for this? I've been experimenting with synchronizing custom fields between translations: so example I store related posts in ACF field and on save all the related posts are synched to translation (posts changed to their translations in the way). I think this would be the way to handle copying over existing content.

I think adding button could be risky as users may easily accidentally click it (if we won't put modals and all kinds of warning in there). If the post is published, by default, all the content is overrided and published straight away which can be bad. If there is no revisions, you can't bring back the old content (without backup database dump).

One way to do this right now is to delete a translation and create a new one or unlink the existing translation (turn it to draft etc) and create a new translation. Am I missing some useful use cases that synchronizing some fields wouldn't cover? Polylang Pro offers a way to even have a same post for multiple languages if that's what you are after (https://polylang.pro/polylang-2-1/)

**Comment by strarsis** [comment]
Good points!
