### ISSUE TITLE
Add support for other custom fields

### ISSUE THREAD

**Issue by strarsis** [aucor/polylang-copy-content#4]
It would be nice if also other custom fields could be copied over like from [Mesh plugin](https://github.com/linchpin/mesh).

**Comment by TeemuSuoranta** [comment]
Hi!

Sorry for a late answer. I did consider adding some sort of custom fields support but found out that Polylang has native filter to add custom fields: https://polylang.pro/doc/filter-reference/#pll_copy_post_metas

Also Polylang states that "Polylang always copies all metadatas from the source post when creating a new translation" https://polylang.pro/doc/synchronize-metadatas-between-translations/

So post_meta should be copied by default. If the custom fields contain post IDs/images etc, the default copying has no translating logic in it unlike this plugin's content part (which means that the original IDs/images in custom fields won't be automatically translated when copied).

Polylang Pro version has more advanced custom field support for example for ACF plugin so if you need that functionality I strongly recommend supporting the original Polylang creator by purchasing the premium version https://polylang.pro/downloads/polylang-pro/
