### ISSUE TITLE
Add support for Gutenberg editor

### ISSUE THREAD

**Issue by strarsis** [aucor/polylang-copy-content#6]
When adding a translation to a post edited in Gutenberg editor, 
the new translation doesn't contain the (duplicated) content of original post.
the editor is empty then.

**Comment by TeemuSuoranta** [comment]
This is probably an issue with the hook that the plugin uses. Gutenberg likely won't use the same hook as the old editor but this might be as simple fix as hooking into another action.

I'm not actively using this plugin anymore in new projects as Polylang Pro offers more robust Copy Content functionality but I'd still like to keep this functional.

If you want to dig around and try to solve this yourself, I'll gladly take PR. It takes probably a week or two before I can look into this.

**Comment by TeemuSuoranta** [comment]
I'm building support in another branch https://github.com/aucor/polylang-copy-content/tree/gutenberg-support

Can you help me test if it's working correctly. I have tested image and gallery blocks but it needs still more testing before relasing it.

**Comment by zArubaru** [comment]
@TeemuSuoranta, tested with multiple custom blocks, and seems to work flawlessly. Great work!

**Comment by strarsis** [comment]
@TeemuSuoranta: Can this be merged and released? 🐈

**Comment by zArubaru** [comment]
@strarsis You can try it out with `composer require aucor/polylang-copy-content:dev-gutenberg-support` before that!

**Comment by TeemuSuoranta** [comment]
Sorry to keep you waiting. Thank you for testing it out! The Gutenberg support is now released as I merger the dev-gutenberg-spport branch and updated the readme.
